PR with suggestions - [Improvement]: Help streamline / simplify dependency review action README
actions/dependency-review-action pull request #773
Opened 2024-05-24 07:44 UTC by am-stead

Linked to: "[[Improvement]: Help streamline / simplify dependency review action README#14071](https://github.com/github/docs-content/issues/14071)"

Suggestions made: 
- Added TOC for easier navigation
- Re-worked intro into an "Overview" section and a "Viewing your results" sub-section.
   - Added some info on where/how to find job logs / job summary. (Needs checking for accuracy)
- Re-structured content into new heading and sub-headings. 
  - Re-structured "Installation" and added mini TOC ("Installation (Standard)", "Installation (GitHub Enterprise Server)"
  - Re-configured "Configuration options" section into "Configuration" and added mini TOC to two sub-sections: "Configuration options" and "Configuration methods".
  - Merged existing table notes and considerations for configuration options into one "Notes" sections after the large table. 
  - Split "configuration methods" into two sub-sub-sections ("Option 1: Using inline configuration..." and "Option 2: Using an external configuration file")
  - Re-worked same content for clarity - into set procedural steps. 
- Kept final sections as they are (Outputs, Blocking pull requests [re-named section heading to something more explanative], Getting help, Contributing, Licenses)
- Updated GHES links to "enterprise-server@**latest**" (e.g.) `https://docs.github.com/en/enterprise-server@latest/admin/code-security/managing-github-advanced-security-for-your-enterprise/enabling-github-advanced-security-for-your-enterprise` (The existing links link out to GHES 3.8 (soon to be deprecated), so this will keep the links up to date.) 
- Added a link to docs for general info on dependency review (suggestion)

To do:
- For "Outputs" - what is outputs used for? I would like to add an intro line here, but I'm not sure what to put. Could you advise?

2024-05-24 07:47 UTC, am-stead commented
:wave: @jonjanego 

This week I took a look at the README for dependency-review-action. I have made some suggestions for your consideration (summarised above). ✨

2024-05-24 07:48 UTC, am-stead commented on README.md
> +[TODO: Insert overview line here - what does output refer to? What / how it is used?]
It would be good to add some sort of intro line here? But I wasn't sure what to put...

2024-05-24 18:37 UTC, jonjanego requested changes
this is _AMAZING_ thank you @am-stead 

i have filled in the "TODO" content and added a formatting suggestion

2024-05-27 07:15 UTC, am-stead commented on README.md
>  - `denied-changes` holds information about denied dependency changes in a JSON format.
```suggestion
  - `vulnerable-changes` holds information about dependency changes with vulnerable dependencies in a JSON format.
  - `invalid-license-changes` holds information about invalid or non-compliant license dependency changes in a JSON format.
  - `denied-changes` holds information about denied dependency changes in a JSON format.
```

2024-05-27 07:17 UTC, am-stead commented on README.md
>  - `vulnerable-changes` holds information about dependency changes with vulnerable dependencies in a JSON format.
I've indented these now to match `vulnerable-changes`!

2024-05-28 14:58 UTC, jonjanego requested changes
one suggested removal, one comment.

thx!

2024-05-30 11:14 UTC, am-stead commented on README.md
> +> [!NOTE]
I've pushed an update for this change now! 👍

2024-05-30 14:23 UTC, jonjanego approved these changes

2024-05-30 14:23 UTC, jonjanego commented on README.md
> +> [!NOTE]
fantastic. merging!

2024-05-30 14:23 UTC, merged

2024-08-13 21:29 UTC, TaZ1312 approved these changes